name: appsflyer_sdk
description: A Flutter plugin for AppsFlyer SDK. Supports iOS and Android.
version: 7.0.0

homepage: https://github.com/AppsFlyerSDK/flutter_appsflyer_sdk

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
  mockito: ^5.0.10
  effective_dart: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appsflyer.appsflyersdk
        pluginClass: AppsflyerSdkPlugin
      ios:
        pluginClass: AppsflyerSdkPlugin
        package: com.appsflyer.appsflyersdk
